# Generated by Django 3.2.21 on 2023-09-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_g9rj5z', upload_to='images/'),
        ),
    ]
